/* Generated by Pyrex 0.8.2 on Thu Sep 11 09:16:45 2003 */

#include "Python.h"
#include "structmember.h"


static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, char *name); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char *__pyx_f[];

/* Declarations from sphere */


/* Implementation of sphere */


static PyObject *__pyx_f_6sphere_6Sphere___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6sphere_6Sphere___init__[] = "Sphere with center C and radius R";
static PyMethodDef __pyx_mdef_6sphere_6Sphere___init__ = {"__init__", (PyCFunction)__pyx_f_6sphere_6Sphere___init__, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6sphere_6Sphere___init__};
static PyObject *__pyx_f_6sphere_6Sphere___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_c = 0;
  PyObject *__pyx_v_r = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  static char *__pyx_argnames[] = {"self","c","r",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_c, &__pyx_v_r)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_c);
  Py_INCREF(__pyx_v_r);

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":15 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_r, __pyx_1, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_2 = __pyx_2 > 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__pyx_2) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  }

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":16 */
  if (PyObject_SetAttrString(__pyx_v_self, "c", __pyx_v_c) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":17 */
  if (PyObject_SetAttrString(__pyx_v_self, "r", __pyx_v_r) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":18 */
  __pyx_1 = PyNumber_Multiply(__pyx_v_r, __pyx_v_r); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_v_self, "r2", __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":19 */
  if (PyObject_SetAttrString(__pyx_v_self, "material", Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("sphere.Sphere.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_c);
  Py_DECREF(__pyx_v_r);
  return __pyx_r;
}

static char (__pyx_k3[]) = "I";
static char (__pyx_k4[]) = "t";
static char (__pyx_k5[]) = "P";
static char (__pyx_k6[]) = "N";
static char (__pyx_k7[]) = "prim";

static PyObject *__pyx_f_6sphere_6Sphere_intersect(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_6sphere_6Sphere_intersect = {"intersect", (PyCFunction)__pyx_f_6sphere_6Sphere_intersect, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_6sphere_6Sphere_intersect(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_Ro = 0;
  PyObject *__pyx_v_Rd = 0;
  PyObject *__pyx_v_L;
  PyObject *__pyx_v_D;
  PyObject *__pyx_v_L2;
  PyObject *__pyx_v_M2;
  PyObject *__pyx_v_Q;
  PyObject *__pyx_v_t;
  PyObject *__pyx_v_P;
  PyObject *__pyx_v_N;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"self","Ro","Rd",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_Ro, &__pyx_v_Rd)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_Ro);
  Py_INCREF(__pyx_v_Rd);
  __pyx_v_L = Py_None; Py_INCREF(__pyx_v_L);
  __pyx_v_D = Py_None; Py_INCREF(__pyx_v_D);
  __pyx_v_L2 = Py_None; Py_INCREF(__pyx_v_L2);
  __pyx_v_M2 = Py_None; Py_INCREF(__pyx_v_M2);
  __pyx_v_Q = Py_None; Py_INCREF(__pyx_v_Q);
  __pyx_v_t = Py_None; Py_INCREF(__pyx_v_t);
  __pyx_v_P = Py_None; Py_INCREF(__pyx_v_P);
  __pyx_v_N = Py_None; Py_INCREF(__pyx_v_N);

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":24 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "c"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_2 = PyNumber_Subtract(__pyx_1, __pyx_v_Ro); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_L);
  __pyx_v_L = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":25 */
  __pyx_1 = PyNumber_Multiply(__pyx_v_L, __pyx_v_Rd); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_v_D);
  __pyx_v_D = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":26 */
  __pyx_2 = PyNumber_Multiply(__pyx_v_L, __pyx_v_L); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  Py_DECREF(__pyx_v_L2);
  __pyx_v_L2 = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":28 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_D, __pyx_1, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  __pyx_3 = __pyx_3 < 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_3) {
    __pyx_2 = PyObject_GetAttrString(__pyx_v_self, "r2"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_L2, __pyx_2, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    __pyx_3 = __pyx_3 > 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }
  if (__pyx_3) {

    /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":29 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":31 */
  __pyx_1 = PyNumber_Multiply(__pyx_v_D, __pyx_v_D); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_2 = PyNumber_Subtract(__pyx_v_L2, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_M2);
  __pyx_v_M2 = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":33 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "r2"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_M2, __pyx_1, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_3 = __pyx_3 > 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_3) {

    /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":34 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":36 */
  __pyx_2 = __Pyx_GetName(__pyx_m, "math"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttrString(__pyx_2, "sqrt"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttrString(__pyx_v_self, "r2"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  __pyx_4 = PyNumber_Subtract(__pyx_2, __pyx_v_M2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_Q);
  __pyx_v_Q = __pyx_4;
  __pyx_4 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":38 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "r2"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_L2, __pyx_1, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  __pyx_3 = __pyx_3 > 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_3) {

    /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":39 */
    __pyx_2 = PyNumber_Subtract(__pyx_v_D, __pyx_v_Q); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_DECREF(__pyx_v_t);
    __pyx_v_t = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":41 */
    __pyx_4 = PyNumber_Add(__pyx_v_D, __pyx_v_Q); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
    Py_DECREF(__pyx_v_t);
    __pyx_v_t = __pyx_4;
    __pyx_4 = 0;
  }
  __pyx_L4:;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":43 */
  __pyx_1 = PyNumber_Multiply(__pyx_v_t, __pyx_v_Rd); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_2 = PyNumber_Add(__pyx_v_Ro, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_P);
  __pyx_v_P = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":44 */
  __pyx_4 = PyObject_GetAttrString(__pyx_v_self, "c"); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_1 = PyNumber_Subtract(__pyx_v_P, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyObject_GetAttrString(__pyx_1, "normalize"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_N);
  __pyx_v_N = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":46 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_4 = PyString_FromString(__pyx_k3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_2, __pyx_4, __pyx_v_Rd) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = PyString_FromString(__pyx_k4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_v_t) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyString_FromString(__pyx_k5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_2, __pyx_4, __pyx_v_P) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_1 = PyString_FromString(__pyx_k6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_2, __pyx_1, __pyx_v_N) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyString_FromString(__pyx_k7); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_2, __pyx_4, __pyx_v_self) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("sphere.Sphere.intersect");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_L);
  Py_DECREF(__pyx_v_D);
  Py_DECREF(__pyx_v_L2);
  Py_DECREF(__pyx_v_M2);
  Py_DECREF(__pyx_v_Q);
  Py_DECREF(__pyx_v_t);
  Py_DECREF(__pyx_v_P);
  Py_DECREF(__pyx_v_N);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_Ro);
  Py_DECREF(__pyx_v_Rd);
  return __pyx_r;
}

static char (__pyx_k8[]) = "Sphere(c=%s, r=%.2f)";

static PyObject *__pyx_f_6sphere_6Sphere___str__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_6sphere_6Sphere___str__ = {"__str__", (PyCFunction)__pyx_f_6sphere_6Sphere___str__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_6sphere_6Sphere___str__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":49 */
  __pyx_1 = PyString_FromString(__pyx_k8); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttrString(__pyx_v_self, "c"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttrString(__pyx_v_self, "r"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyNumber_Remainder(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("sphere.Sphere.__str__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static char (__pyx_k1[]) = "math";
static char (__pyx_k2[]) = "Sphere";

DL_EXPORT(void) initsphere(void); /*proto*/
DL_EXPORT(void) initsphere(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_m = Py_InitModule4("sphere", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  __pyx_b = PyImport_AddModule("__builtin__");
  PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b);

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":10 */
  __pyx_1 = PyString_FromString(__pyx_k1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  __pyx_2 = __Pyx_Import(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttrString(__pyx_m, "math", __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":12 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_k2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  __pyx_4 = PyClass_New(__pyx_3, __pyx_1, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":13 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_6sphere_6Sphere___init__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_3 = PyMethod_New(__pyx_2, 0, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttrString(__pyx_4, "__init__", __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":21 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_6sphere_6Sphere_intersect, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  __pyx_3 = PyMethod_New(__pyx_2, 0, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttrString(__pyx_4, "intersect", __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx":48 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_6sphere_6Sphere___str__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  __pyx_3 = PyMethod_New(__pyx_2, 0, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttrString(__pyx_4, "__str__", __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttrString(__pyx_m, "Sphere", __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("sphere");
}

statichere char *__pyx_f[] = {
  "/Users/bhammond/dev/3d/PyTrace/pytrace/primitives/sphere.pyx",
};

/* Runtime support code */

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
  PyObject *__import__ = 0;
  PyObject *empty_list = 0;
  PyObject *module = 0;
  PyObject *global_dict = 0;
  PyObject *empty_dict = 0;
  PyObject *list;
  __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
  if (!__import__)
    goto bad;
  if (from_list)
    list = from_list;
  else {
    empty_list = PyList_New(0);
    if (!empty_list)
      goto bad;
    list = empty_list;
  }
  global_dict = PyModule_GetDict(__pyx_m);
  if (!global_dict)
    goto bad;
  empty_dict = PyDict_New();
  if (!empty_dict)
    goto bad;
  module = PyObject_CallFunction(__import__, "OOOO",
    name, global_dict, empty_dict, list);
bad:
  Py_XDECREF(empty_list);
  Py_XDECREF(__import__);
  Py_XDECREF(empty_dict);
  return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, char *name) {
  PyObject *result;
  result = PyObject_GetAttrString(dict, name);
  if (!result)
    PyErr_SetString(PyExc_NameError, name);
  return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
  PyObject *py_srcfile = 0;
  PyObject *py_funcname = 0;
  PyObject *py_globals = 0;
  PyObject *empty_tuple = 0;
  PyObject *empty_string = 0;
  PyCodeObject *py_code = 0;
  PyFrameObject *py_frame = 0;
  
  py_srcfile = PyString_FromString(__pyx_filename);
  if (!py_srcfile) goto bad;
  py_funcname = PyString_FromString(funcname);
  if (!py_funcname) goto bad;
  py_globals = PyModule_GetDict(__pyx_m);
  if (!py_globals) goto bad;
  empty_tuple = PyTuple_New(0);
  if (!empty_tuple) goto bad;
  empty_string = PyString_FromString("");
  if (!empty_string) goto bad;
  py_code = PyCode_New(
    0,            /*int argcount,*/
    0,            /*int nlocals,*/
    0,            /*int stacksize,*/
    0,            /*int flags,*/
    empty_string, /*PyObject *code,*/
    empty_tuple,  /*PyObject *consts,*/
    empty_tuple,  /*PyObject *names,*/
    empty_tuple,  /*PyObject *varnames,*/
    empty_tuple,  /*PyObject *freevars,*/
    empty_tuple,  /*PyObject *cellvars,*/
    py_srcfile,   /*PyObject *filename,*/
    py_funcname,  /*PyObject *name,*/
    __pyx_lineno,   /*int firstlineno,*/
    empty_string  /*PyObject *lnotab*/
  );
  if (!py_code) goto bad;
  py_frame = PyFrame_New(
    PyThreadState_Get(), /*PyThreadState *tstate,*/
    py_code,             /*PyCodeObject *code,*/
    py_globals,          /*PyObject *globals,*/
    0                    /*PyObject *locals*/
  );
  if (!py_frame) goto bad;
  py_frame->f_lineno = __pyx_lineno;
  PyTraceBack_Here(py_frame);
bad:
  Py_XDECREF(py_srcfile);
  Py_XDECREF(py_funcname);
  Py_XDECREF(empty_tuple);
  Py_XDECREF(empty_string);
  Py_XDECREF(py_code);
  Py_XDECREF(py_frame);
}
